#!/bin/bash
#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.
#
# package a cordova project into a cdvh for app harness (zip file with a specific file and folder layout)
#
# USAGE
#   ./packapp project_directory [packageName.cdvh]

USAGE_STRING="Usage: packapp [-p] project_directory [packageName.cdvh]\n\t-p Runs cordova prepare before packaging the app"

if [ $# -lt 1 ]
then
  echo -e $USAGE_STRING
  exit -1
fi

RUN_PREPARE=

while getopts ":hp" option; do
  case $option in
    h) echo -e $USAGE_STRING; exit ;;
    p) RUN_PREPARE=1 ;;
    ?) echo "error: option -$OPTARG is not implemented"; exit ;;
  esac
done

# remove the options from the positional parameters
shift $(( OPTIND - 1 ))

ORIG_DIR=$(pwd)

# switch to project directory
cd $1

if [ ! -z "$RUN_PREPARE" ]
then
    echo "Running Prepare"
    cordova prepare
fi

FILE_NAME=$(basename "`pwd`" ).cdvh

if [ $# -ge 2 ]
then
    FILE_NAME=$2
fi

mkdir packtempDir

if [ -d "./platforms/android" ]
then
    echo "Platform: android found"
    mkdir packtempDir/android
    cp -f ./platforms/android/res/xml/config.xml ./packtempDir/android/config.xml
    cp -rf ./platforms/android/assets/www ./packtempDir/android/www
fi
if [ -d "./platforms/ios" ]
then
    echo "Platform: ios found"
    mkdir packtempDir/ios
    IOS_PROJ_DIR=$(find ./platforms/ios -name config.xml -exec dirname {} \;)
    cp -f $IOS_PROJ_DIR/config.xml ./packtempDir/ios/config.xml
    cp -rf ./platforms/ios/www ./packtempDir/ios/www
fi

cd packtempDir
zip -r $ORIG_DIR/$FILE_NAME android ios >/dev/null
cd ..
# rm -rf packtempDir