#!/bin/bash
#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.
#
# package a cordova project into a zip for app harness
#
# USAGE
#   ./zipapp project_directory [zipfileName]
#
if [ $# -lt 1 ]
then
  echo "Usage: zipapp project_directory [zipfileName]"
  exit -1
fi

ORIG_DIR=$(pwd)


cd $1
FILE_NAME=$(basename "`pwd`" ).zip

if [ $# -ge 2 ]
then
    FILE_NAME=$2
fi

if [ -d "./platforms/android" ]
then
    echo "Platform: android found"
    cp -f ./platforms/android/res/xml/config.xml ./app/config.android.xml
    if [ -f "./app/config.android.xml" ]
    then
        echo "Platform: android added successfully"
    else
        echo "Unable to locate config.xml for android"
    fi
fi

if [ -d "./platforms/ios" ]
then
    echo "Platform: ios found"
    find ./platforms/ios/ -name config.xml -exec cp {} ./app/config.ios.xml \;
    if [ -f "./app/config.ios.xml" ]
    then
        echo "Platform: ios added successfully"
    else
        echo "Unable to locate config.xml for ios"
    fi
fi


cd ./app
zip -r $ORIG_DIR/$FILE_NAME www config.*.xml

rm config.*.xml